x-google-marketplace:
  schemaVersion: v2

  applicationApiVersion: v1beta1

  publishedVersion: "3.0.0"
  publishedVersionMetadata:
    releaseNote: >-
      A first release.

  clusterConstraints:
    resources:
    - replicas: 1
      requests:
        cpu: 100m
        memory: 300Mi

  images:
    '':  # Primary image has no name.
      properties:
        imageRepo:
          type: REPO_WITH_REGISTRY
        imageTag:
          type: TAG

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
      default: falcon-integration-gateway
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
      default: falcon-gateway
  falcon.cloud_region:
    title: Falcon Cloud Region
    type: string
    x-google-marketplace:
      type: STRING
    default: us-1
    enum:
    - 'us-1'
    - 'us-2'
    - 'eu-1'
    - 'us-gov-1'
  falcon.client_id:
    title: "Falcon API OAuth2 Credentials: Client ID"
    type: string
    x-google-marketplace:
      type: MASKED_FIELD
  falcon.client_secret:
    title: "Falcon API OAuth2 Credentials: Client Secret"
    type: string
    x-google-marketplace:
      type: MASKED_FIELD
  cloud.google.application_credentials:
    title: "GCP Service Account key for accessing SCC (base64 encoded)"
    type: string
    x-google-marketplace:
      type: MASKED_FIELD

required:
- name
- namespace
- falcon.client_id
- falcon.client_secret
- falcon.cloud_region
- cloud.google.application_credentials

form:
- widget: help
  description: |-
    <a href="https://github.com/CrowdStrike/falcon-integration-gateway/blob/main/docs/listings/gke/UserGuide.md">Deployment Guide</a>
