x-google-marketplace:
  schemaVersion: v2

  applicationApiVersion: v1beta1

  publishedVersion: "3.3.0"
  publishedVersionMetadata:
    releaseNote: >-
      3.1
      Updated to the latest Google Cloud API (SCC & Chronicle)

      3.0
      A first release.

  clusterConstraints:
    resources:
      - replicas: 1
        requests:
          cpu: 100m
          memory: 300Mi

  images:
    "": # Primary image has no name.
      properties:
        imageRepo:
          type: REPO_WITH_REGISTRY
        imageTag:
          type: TAG

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
      default: falcon-integration-gateway
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
      default: falcon-gateway
  falcon.cloud_region:
    title: Falcon Cloud Region
    type: string
    x-google-marketplace:
      type: STRING
    default: us-1
    enum:
      - "us-1"
      - "us-2"
      - "eu-1"
      - "us-gov-1"
  falcon.client_id:
    title: "Falcon API OAuth2 Credentials: Client ID"
    description: "API keypair used to authenticate with Falcon Platform and to initiate streaming session. Only the following permissions are required: READ 'Event streams' and READ 'Hosts'"
    type: string
    x-google-marketplace:
      type: MASKED_FIELD
  falcon.client_secret:
    title: "Falcon API OAuth2 Credentials: Client Secret"
    description: "API keypair used to authenticate with Falcon Platform and to initiate streaming session. Only the following permissions are required: READ 'Event streams' and READ 'Hosts'"
    type: string
    x-google-marketplace:
      type: MASKED_FIELD
  cloud.google.application_credentials:
    title: "GCP Service Account key for accessing SCC (base64 encoded)"
    description: "This service account will be used to create Falcon Findings in GCP Security Command Center. Falcon Integration Gateway is able to automatically discover GCP projects and organizations it has access to. Consult the User Guide for more information."
    type: string
    x-google-marketplace:
      type: MASKED_FIELD

required:
  - name
  - namespace
  - falcon.client_id
  - falcon.client_secret
  - falcon.cloud_region
  - cloud.google.application_credentials

form:
  - widget: help
    description: |-
      <a href="https://github.com/CrowdStrike/falcon-integration-gateway/blob/main/docs/listings/gke/UserGuide.md">Deployment Guide</a>
