apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "falcon-integration-gateway.fullname" . }}-creds
  labels:
    {{- include "falcon-integration-gateway.labels" . | nindent 4 }}
data:
  FALCON_CLIENT_ID: {{ .Values.falcon.client_id | b64enc }}
  FALCON_CLIENT_SECRET: {{ .Values.falcon.client_secret | b64enc }}
{{- if .Values.chronicle.enabled }}
  GOOGLE_CUSTOMER_ID: {{ .Values.chronicle.google_customer_id | b64enc }}
  GOOGLE_SERVICE_ACCOUNT_FILE: {{ .Values.chronicle.google_service_account_file }}
{{- end }}
