x-google-marketplace:
  schemaVersion: v2

  applicationApiVersion: v1beta1

  publishedVersion: "3.1.12"
  publishedVersionMetadata:
    releaseNote: >-
      3.1
      Updated to the latest Google Cloud API (SCC & Chronicle)

      3.0
      A first release.

  clusterConstraints:
    resources:
    - replicas: 1
      requests:
        cpu: 100m
        memory: 300Mi

  images:
    '':  # Primary image has no name.
      properties:
        imageRepo:
          type: REPO_WITH_REGISTRY
        imageTag:
          type: TAG

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
      default: falcon-integration-gateway
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
      default: falcon-gateway
  falcon.cloud_region:
    title: Falcon Cloud Region
    type: string
    x-google-marketplace:
      type: STRING
    default: us-1
    enum:
    - 'us-1'
    - 'us-2'
    - 'eu-1'
    - 'us-gov-1'
  falcon.client_id:
    title: "Falcon API OAuth2 Credentials: Client ID"
    description: "API keypair used to authenticate with Falcon Platform and to initiate streaming session. Only the following permissions are required: READ 'Event streams' and READ 'Hosts'"
    type: string
    x-google-marketplace:
      type: MASKED_FIELD
  falcon.client_secret:
    title: "Falcon API OAuth2 Credentials: Client Secret"
    description: "API keypair used to authenticate with Falcon Platform and to initiate streaming session. Only the following permissions are required: READ 'Event streams' and READ 'Hosts'"
    type: string
    x-google-marketplace:
      type: MASKED_FIELD
  chronicle.region:
    type: string
    x-google-marketplace:
      type: STRING
    default: us
  chronicle.google_customer_id:
    description: "This customer id will be used to push Falcon detections findings to Chronicle. Consult the User Guide for more information."
    type: string
    x-google-marketplace:
      type: MASKED_FIELD
  chronicle.google_service_account_file:
    title: "GCP Service Account key for accessing Chronicle (base64 encoded)"
    description: "This service account will be used to create Findings in Chronicle. Consult the User Guide for more information."
    type: string
    x-google-marketplace:
      type: MASKED_FIELD

required:
- name
- namespace
- falcon.client_id
- falcon.client_secret
- falcon.cloud_region
- chronicle.google_customer_id
- chronicle.region

form:
- widget: help
  description: |-
    <a href="https://github.com/CrowdStrike/falcon-integration-gateway/blob/main/docs/listings/gke-chronicle/UserGuide.md">Deployment Guide</a>
