x-google-marketplace:
  schemaVersion: v2

  applicationApiVersion: v1beta1

  publishedVersion: "3.0.0"
  publishedVersionMetadata:
    releaseNote: >-
      A first release.

  clusterConstraints:
    resources:
    - replicas: 1
      requests:
        cpu: 100m
        memory: 300Mi

  images:
    '':  # Primary image has no name.
      properties:
        imageRepo:
          type: REPO_WITH_REGISTRY
        imageTag:
          type: TAG

properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
      default: falcon-integration-gateway-chronicle
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
      default: falcon-gateway
  falcon.cloud_region:
    type: string
    x-google-marketplace:
      type: STRING
    default: us-1
  falcon.client_id:
    type: string
    x-google-marketplace:
      type: MASKED_FIELD
  falcon.client_secret:
    type: string
    x-google-marketplace:
      type: MASKED_FIELD
  chronicle.region:
    type: string
    x-google-marketplace:
      type: STRING
    default: us
  chronicle.google_security_key:
    type: string
    x-google-marketplace:
      type: MASKED_FIELD

required:
- name
- namespace
- falcon.client_id
- falcon.client_secret
- falcon.cloud_region
- chronicle.google_security_key
- chronicle.region

form:
- widget: help
  description: |-
    <a href="https://github.com/CrowdStrike/falcon-integration-gateway/blob/main/docs/listings/gke-chronicle/UserGuide.md">Deployment Guide</a>
