properties:
  falcon.client_id:
    type: string
    x-google-marketplace:
      type: MASKED_FIELD
    default: MARKETPLACE_TEST
  falcon.client_secret:
    type: string
    x-google-marketplace:
      type: MASKED_FIELD
    default: MARKETPLACE_TEST
  chronicle.google_security_key:
    type: string
    x-google-marketplace:
      type: MASKED_FIELD
    default: TUFSS0VUUExBQ0VfVEVTVA==
