properties:
  falcon.client_id:
    type: string
    x-google-marketplace:
      type: MASKED_FIELD
    default: MARKETPLACE_TEST
  falcon.client_secret:
    type: string
    x-google-marketplace:
      type: MASKED_FIELD
    default: MARKETPLACE_TEST
  chronicle.google_customer_id:
    type: string
    x-google-marketplace:
      type: MASKED_FIELD
    default: TUFSS0VUUExBQ0VfVEVTVA==
  chronicle.google_service_account_file:
    type: string
    x-google-marketplace:
      type: MASKED_FIELD
    default: TUFSS0VUUExBQ0VfVEVTVA==
